title: "Programming Dog"
description: "Love Technology and Life"
url: "https://programmingdog.github.io"

# 主题选择（二选一）
theme: minima
# remote_theme: 用户名/仓库名

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

lang: en-US
timezone: Asia/Shanghai
